### ISSUE TITLE
Example is not working. Giving following error while pushing data to docker zipkin server.

### ISSUE THREAD

**Issue by vsachinv** [hyleung/ratpack-zipkin-example#1]
@hyleung Could you please help here?

`WARNING: Dropped 2 spans due to TTransportException(Frame size (1213486160) larger than max length (16384000)!)
org.apache.thrift.transport.TTransportException: Frame size (1213486160) larger than max length (16384000)!
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at zipkin.reporter.libthrift.InternalScribeCodec.readLogResponse(InternalScribeCodec.java:59)
	at zipkin.reporter.libthrift.ScribeClient.log(ScribeClient.java:51)
	at zipkin.reporter.libthrift.LibthriftSender.sendSpans(LibthriftSender.java:94)
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:245)
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:166)
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hyleung** [comment]
@vsachinv I'll take a look - you're using just using the current `docker-zipkin` setup?

**Comment by hyleung** [comment]
@vsachinv did this happen under load? I haven't seen this in manual testing but was able to reproduce it in a load test with a high number of concurrent requests.

**Comment by vsachinv** [comment]
@hyleung It happened in normal run. I had setup docker-zipkin run on 9410 port and run the example by putting scribeHost as localhost.

**Comment by hyleung** [comment]
@vsachinv hmm...give this branch a try - https://github.com/hyleung/ratpack-zipkin-example/pull/2. I've upgraded the libs (I needed to do this at some point anyway). I re-ran my load test and didn't see any dropped spans. Also - just to make sure we're on the same page - do a `docker-compose pull` on `docker-zipkin` to make sure you've got the latest images.

**Comment by vsachinv** [comment]
@hyleung Thanks! I will check it out. But I got it working by adding OkHTTPSender support.

> https://github.com/vsachinv/ratpack-zipkin-example/tree/okHttpSenderSupport

**Comment by hyleung** [comment]
@vsachinv good to hear you got it working. I got it working with Scribe when I upgraded the libs, but in the near future I'll probably remove Scribe from this example because it's not enabled by default in `docker-zipkin` anyway. Much easier to get going with OKHttp because you don't need to modify the `docker-compose.yml` files to enable Scribe. 

If it's ok with you, I'll close this issue...
